# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Position Controllers ---------------------------------------
joint1_position_controller:
  type: effort_controllers/JointPositionController
  joint: base_link__link1
  pid: {p: 700.0, i: 50, d: 70.0}
joint2_position_controller:
  type: effort_controllers/JointPositionController
  joint: link1_link2
  pid: {p: 700.0, i: 50, d: 70.0}

#joint3_position_controller:
  #type: effort_controllers/JointPositionController
 # joint: link2_link3
  #pid: {p: 20000.0, i: 50, d: 1000.0}
#joint4_position_controller:
 # type: effort_controllers/JointPositionController
  #joint: link_03__link_04
  #pid: {p: 2000.0, i: 50, d: 200.0}
#joint5_position_controller:
 # type: effort_controllers/JointPositionController
  #joint: link_04__link_05
  #pid: {p: 700.0, i: 50, d: 70.0}
