controller_list:
  - name: fake_arm_controller
    joints:
      - base_link1
      - link1_link2
      - link2_link3
      - link3_link4
      - link4_gripper_base
  - name: fake_hand_controller
    joints:
      - gripper_base_claw_L
      - gripper_base_claw_R